pre:
  - name: "ls pre-task"
    cmd_path: "ls"
    args:
      - /


services:
  - name: "sleep 1"
    cmd_path: "sleep"
    args: ["10"]

  - name: "echo"
    cmd_path: "echo"
    args:
      - Hello
      - world!

  - name: "sleep 2"
    cmd_path: "sleep"
    args: ["30"]
    keepalive: true
    restart_on_failure: true
